### PR TITLE
 Ft member comparison 

### PR DESCRIPTION
**Pull request by Rodgers-M**
**What does this PR do?**
Enables two users training together to have weight data comparison

**Description of tasks to be completed**

- Define endpoints to fetch weight data for the currently logged in user and the user in comparison.
- Implement the necessary Js to plot the graphs.
- Create a template to display the two graphs side by side.
- Have a dropdown to select users to compare with
- Include a comparison tab in the navigation bar

**How can this be tested manually?**

- Navigate to the comparison tab, this should have a graph with the currently logged in user, select another user and their graph will appear on the right side.

**Relevant tracker stories**

- 157110622

**Additional notes**
- this feature requires javascript hence ensure all the static files are loading as expected.

**Screenshots**
Default comparison page

screen shot 2018-05-15 at 2 53 20 pm

Drop down to select a comparison user 

screen shot 2018-05-15 at 2 56 14 pm

A comparison with another user

screen shot 2018-05-15 at 8 07 39 am

Comparison with another different user

screen shot 2018-05-15 at 8 08 16 am

### CODE REVIEW

**Review by paulrimiru — APPROVED** [review]
Good work. Looks Good To Me

**Review by younggeeks — COMMENTED** [review]
Good work. 
Side by side comparison looks good.
Your comments in urls.py  could use an improvement your 
Also add comments in your view methods

**Comment by Rodgers-M** [comment]
Thanks, @younggeeks I will add the comments.

**Comment by MarloneA** [comment]
Nice work making the comparisons visual

**Pull request merged**
